# Utilise une image de base Node.js
FROM node:20.18.0

# Définit le répertoire de travail dans le conteneur
WORKDIR /app

# Copie le fichier package.json et package-lock.json
# Cela permet d'installer les dépendances avant de copier tout le code (pour améliorer la mise en cache)
COPY package*.json ./

# Installe les dépendances
RUN npm install

# Copie le reste du code de ton application
COPY . .

# Expose le port sur lequel l'application va tourner (par défaut 3000 pour Express)
EXPOSE 3000

# Lance l'application Express
CMD ["npm", "start"]
