# Utiliser l'image de base Node.js
FROM node:20

# Définir le répertoire de travail dans le conteneur
WORKDIR /usr/src/app

# Copier les fichiers package.json et package-lock.json dans le conteneur
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers du projet dans le conteneur
COPY . .

# Exposer le port que ton application utilise
EXPOSE 3000

# Démarrer l'application avec nodemon
CMD ["npx", "nodemon", "app.js"]